name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Build with Maven
      run: mvn clean install

    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push docker image to docker hub
      run: mvn compile jib:build -Dimage=docker.io/${{ vars.DOCKERHUB_USERNAME }}/wedding-page:latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Docker image to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@51.20.185.33 << 'EOF'
        sudo usermod -aG docker $USER
        sudo docker pull ${{ vars.DOCKERHUB_USERNAME }}/wedding-page:latest
        sudo docker kill $(docker ps -aq) || true
        docker run -d -p 8080:8080 ${{ vars.DOCKERHUB_USERNAME }}/wedding-page:latest
        EOF